#!/usr/bin/env bash
# Bash script to install nginx on an ubuntu system

sudo apt-get update -y
sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/redirect.html > /dev/null

N_URL='location = /redirect_me {\n\treturn 301 https://www.youtube.com/@youngkingajay;\n}\n'

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup

sudo sed -i "/server {/a $N_URL" /etc/nginx/sites-available/default

sudo service nginx restart
