#!/usr/bin/env bash

# Disable the ipv6 only in the default Nginx configuration
sudo sed -i "s/ipv6only=on//" /etc/nginx/sites-available/default

# The default site configuration symlink to be tkken out
sudo rm -f /etc/nginx/sites-enabled/default

# Create a new symlink for the default site configuration
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx service
sudo service nginx restart
