#!/usr/bin/env bash

#script is concise and achieves the desired task
#short and sweet Bash script that meets requirements
sed -i "s/ipv6only=on/d" /etc/nginx/sites-available/default
rm -f /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
