#!/usr/bin/env bash

# Restore default server port for Nginx and restart it
sed -i '/ipv6only=on/d' /etc/nginx/sites-available/default
rm -f /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart

