#!/usr/bin/env bash
# Displaying the contents of the current directory in list format.
#   Only display the part of the name after the 1st dash. 

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
