#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080.


# OR!!!!
# #!/usr/bin/env bash
# # Fixes a web server to run Nginx as the nginx user listening on port 8080.

# # Exit the script if fails
# set -e

# # Update Nginx configuration
# sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# chmod 644 /etc/nginx/nginx

# # Stop ApachE running
# if pgrep apache2 > /dev/null; then
#   service apache2 stop
# fi

# # Start Nginx as the nginx user
# sudo -u nginx service nginx start



sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod u+rwx /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
