#!/usr/bin/env bash
# Update Nginx configuration
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod u+r /etc/nginx/nginx.conf
# Killing apache from running on server
pgrep apache2 > /dev/null && service apache2 stop
# Start Nginx
service nginx start
